### ISSUE TITLE
Invoking a lambda function does not return payload

### ISSUE THREAD

**Issue by omchiii** [agilord/aws_client#300] opened 2021-01-18 11:08 UTC
```
try {
      CognitoAuthSession session = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));

      AwsClientCredentials cred = AwsClientCredentials(
          accessKey: session.credentials.awsAccessKey,
          secretKey: session.credentials.awsSecretKey,
          sessionToken: session.credentials.sessionToken);

      final service = Lambda(region: region, credentials: cred);

      try {
        List<int> list =
            '{"key1": "value1","key2": "value2","key3": "value3"}'.codeUnits;

        InvocationResponse updateItemOutput = await service.invoke(
            functionName: "amplify-lambda-invoke-test",
            invocationType: InvocationType.event,
            payload: Uint8List.fromList(list));
        print(updateItemOutput.payload);
      } catch (e) {
        print("asd");
        print(e);
      }
    } on AuthError catch (e) {
      print(e);
    }


```

This code snippet successfully invokes a lambda function but it returns a catch error "202 UnknownError: 202". Whereas this functions response should be "Hello from lambda". What am I doing wrong?

**Comment by Schwusch** [comment] 2021-01-18 12:59
This was fixed in https://github.com/agilord/aws_client/commit/c08eb07ae8a6bcec53e920a02fe935cd8cf83f79, although a release hasn't been made since then.

**Comment by omchiii** [comment] 2021-01-18 14:30
> This was fixed in [c08eb07](https://github.com/agilord/aws_client/commit/c08eb07ae8a6bcec53e920a02fe935cd8cf83f79), although a release hasn't been made since then.

I changed the those two lines in the source files. Now I get this "FormatException: Unexpected end of input (at character 1)
" , same code as the above.

**Comment by Schwusch** [comment] 2021-01-18 14:45
I haven't seen that one before, @xvrh something you recognize?
@omchiii Do you have a stacktrace you can share?

**Comment by omchiii** [comment] 2021-01-18 14:59
` final String region = "us-east-1";

    try {
      CognitoAuthSession session = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));

      AwsClientCredentials cred = AwsClientCredentials(
          accessKey: session.credentials.awsAccessKey,
          secretKey: session.credentials.awsSecretKey,
          sessionToken: session.credentials.sessionToken);

      final service = Lambda(region: region, credentials: cred);

      try {
        InvocationResponse updateItemOutput = await service.invoke(
          functionName: "amplify-lambda-invoke-test",
          invocationType: InvocationType.event,
        );
        print("success");
        print(updateItemOutput);
      } catch (e) {
        print("error");
        print(e);
      }
    } on AuthError catch (e) {
      print(e);
    }
  }`


Here is the code again with changed print statements, here is what I get from the debug console.

`flutter: error
flutter: FormatException: Unexpected end of input (at character 1)
^
 `

**Comment by omchiii** [comment] 2021-01-18 15:02
`if (rs.statusCode < 200 || rs.statusCode >= 300) {
      throwException(rs, body, exceptionFnMap);
    }`

I only changed this if statement , both in "json.dart" & "rest-json.dart" from shared_aws_api-0.2.4.

**Comment by xvrh** [comment] 2021-01-18 15:06
I think this is something that will be fixed with the next version too. The body of the response is not a JSON file.
@omchiii you can try to depend on the version in github:

```yaml
dependency_overrides:
  aws_lambda_api:
    git:
      url: https://github.com/agilord/aws_client.git
      ref: e85c9f9
      path: generated/aws_lambda_api
  shared_aws_api:
    git:
      url: https://github.com/agilord/aws_client.git
      ref: e85c9f9
      path: shared_aws_api
```

**Comment by omchiii** [comment] 2021-01-18 15:38
`flutter : success`
`[]` // this is InvokationResponse.payload

First of all thank you @xvrh  & @Schwusch for your help. The response now isn't an exception but there is a different issue, the payload(InvokationResponse.payload) of the invocation is "[]". When I invoke my lambda through AWS Console it returns me "Hello from lambda".

**Comment by omchiii** [comment] 2021-01-18 15:41
` List<int> list =
            '{"key1": "value1","key2": "value2","key3": "value3"}'.codeUnits;

        InvocationResponse lambdaResponse = await service.invoke(
            functionName: "amplify-lambda-invoke-test",
            invocationType: InvocationType.event,
            payload: Uint8List.fromList(list));
        print("sucess");
        print(lambdaResponse.payload);` I tried doing it with and without the payload parameter, same result.

**Comment by xvrh** [comment] 2021-01-18 15:57
@omchiii can you try to print `lambdaResponse.logResult` and `response.functionError` (or inspect the response with a debugger)?
I'm not able to reproduce, I quickly tried with one of my lambda and I'm correctly receiving the response payload...

**Comment by omchiii** [comment] 2021-01-18 16:00
`final String region = "us-east-1";

    try {
      CognitoAuthSession session = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));

      AwsClientCredentials cred = AwsClientCredentials(
          accessKey: session.credentials.awsAccessKey,
          secretKey: session.credentials.awsSecretKey,
          sessionToken: session.credentials.sessionToken);

      final service = Lambda(region: region, credentials: cred);

      try {
        List<int> list =
            '{"key1": "value1","key2": "value2","key3": "value3"}'.codeUnits;

        InvocationResponse lambdaResponse = await service.invoke(
            functionName: "amplify-lambda-invoke-test",
            invocationType: InvocationType.requestResponse,
            payload: Uint8List.fromList(list));
        print("sucess");
        print(String.fromCharCodes(lambdaResponse.payload));
      } catch (e) {
        print("error");
        print(e);
      }
    } on AuthError catch (e) {
      print(e);
    }`

I changed the invocation type to "InvocationType.requestResponse" and now it works. Thank you!

**Comment by xvrh** [comment] 2021-01-18 16:02
OK, you right, with `InvocationType.event` I don't have a result neither. It seems to make sense. From the doc: 
````
<code>Event</code> - Invoke the function asynchronously. Send events that
fail multiple times to the function's dead-letter queue (if it's
configured). The API response only includes a status code.
```

**Comment by omchiii** [comment] 2021-01-18 16:04
> OK, you right, with `InvocationType.event` I don't have a result neither. It seems to make sense. From the doc:
> 
> ```
> <code>Event</code> - Invoke the function asynchronously. Send events that
> fail multiple times to the function's dead-letter queue (if it's
> configured). The API response only includes a status code.
> ```
> ```

Yes, my mistake. I read the documentation but I switched up the two invocation types in my mind.

**Closed** 2021-01-18 16:10 UTC

**Comment by Schwusch** [comment] 2021-01-18 21:35
@omchiii There is now a new release on pub.dev if you don't want to depend on Github in your pubspec.
