### ISSUE TITLE
AWS Image Upload

### ISSUE THREAD

**Issue by caroline171** [agilord/aws_client#1] opened 2019-01-23 12:48 UTC
Is there any means now to use the library now for uploading AWS photos to an S3 storage bucket ?

**Comment by isoos** [comment] 2019-01-23 22:58
Sorry that hasn't been implemented in this library yet.

**Comment by Schwusch** [comment] 2020-04-20 18:16
@caroline171 Have you tried the generated package?
https://pub.dev/packages/aws_s3_api

**Comment by Schwusch** [comment] 2020-06-01 20:07
I'll close this, assuming the problem is solved

**Closed by Schwusch** 2020-06-01 20:07 UTC
